/// Flutter icons DBIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
// flutter:
//   fonts:
//    - family:  DBIcons
//      fonts:
//       - asset: fonts/DBIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DBIcons {
  DBIcons._();

  static const _kFontFam = 'DBIcons';
  static const String? _kFontPkg = null;

  static const IconData menu = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData augmented_reality = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
